package ctxkey

const (
	Config            = "config"
	Id                = "id"
	Username          = "username"
	Role              = "role"
	Status            = "status"
	Channel           = "channel"
	ChannelId         = "channel_id"
	SpecificChannelId = "specific_channel_id"
	RequestModel      = "request_model"
	ConvertedRequest  = "converted_request"
	OriginalModel     = "original_model"
	Group             = "group"
	ModelMapping      = "model_mapping"
	ChannelName       = "channel_name"
	TokenId           = "token_id"
	TokenName         = "token_name"
	BaseURL           = "base_url"
	AvailableModels   = "available_models"
	KeyRequestBody    = "key_request_body"
	SystemPrompt      = "system_prompt"
	ZeoCredentialId   = "zeo_credential_id"
	ZeoTenantId       = "zeo_tenant_id"
	ZeoProfile        = "zeo_profile"
	ZeoAllowedSites   = "zeo_allowed_sites"
	ZeoReserved       = "zeo_reserved_tokens"
	ZeoFirstByteMs    = "zeo_first_byte_ms"
	ZeoRequestStart   = "zeo_request_start"
)
